# thu cli command configuration example

#[environ]
#AWS_PROFILE = "toshi_batch_devops"
#NZSHM22_HAZARD_STORE_STAGE = "PROD"
#REGION = "ap-southeast-2"

[report]
hazard_model_ids = "HAZARD_MODEL_TEST_1, SLT_TAG_FINAL"
vs30s = [ 400 ]
# sites = "-44.23~172.33"
sites = "-41.3~174.78, -37.78~175.28" #WLG,HLZ