# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-test-workflow:
    uses: GNS-Science/nshm-github-actions/.github/workflows/python-run-tests.yml@main
    with:
      operating-systems: "['ubuntu-18.04', 'macos-latest', 'windows-latest']"
      python-versions: "['3.8', '3.9', '3.10']"
      poetry-version: 1.8.5 # support for 3.8 is dropped after this
    secrets: inherit

